let offers=JSON.parse(localStorage.getItem("ads_offers")||"[]"), queue=JSON.parse(localStorage.getItem("ads_queue")||"[]"), history=JSON.parse(localStorage.getItem("ads_history")||"[]"), groups=JSON.parse(localStorage.getItem("ads_groups")||"[]");
const titles={inicio:"Início",ofertas:"Ofertas",criar:"Criar divulgação",fila:"Fila de publicação",historico:"Histórico",grupos:"Grupos",config:"Configurações"};
function showPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));document.getElementById("pageTitle").textContent=titles[id];render();document.querySelector(".sidebar").classList.remove("open")}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>showPage(b.dataset.page));
document.getElementById("menuBtn").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");
function save(){localStorage.setItem("ads_offers",JSON.stringify(offers));localStorage.setItem("ads_queue",JSON.stringify(queue));localStorage.setItem("ads_history",JSON.stringify(history));localStorage.setItem("ads_groups",JSON.stringify(groups))}
function saveOffer(){let name=document.getElementById("productName").value.trim()||"Produto da Shopee",price=document.getElementById("price").value.trim(),old=document.getElementById("oldPrice").value.trim(),link=document.getElementById("productLink").value.trim(),aff=document.getElementById("affiliateLink").value.trim();if(!price||!link){alert("Preencha o preço e o link do produto.");return}if(!/^https?:\\/\\//i.test(link)){alert("Informe um link válido do produto.");return}let o={id:Date.now(),name,price,old,link,aff,category:document.getElementById("category").value,date:new Date().toLocaleString("pt-BR")};offers.unshift(o);queue.push(o);save();document.getElementById("productName").value="";document.getElementById("price").value="";document.getElementById("oldPrice").value="";document.getElementById("productLink").value="";document.getElementById("affiliateLink").value="";makePreview(o);alert("Oferta salva e colocada na fila!")}
function makePreview(o){document.getElementById("preview").innerHTML=`<h3>Prévia da divulgação</h3><div class="preview-box">🔥 OLHA ESSE ACHADINHO!\\n\\n🛍️ ${o.name}\\n💰 Por apenas ${o.price}${o.old?" (antes "+o.old+")":""}\\n\\n🛒 COMPRE AQUI:\\n${o.aff||o.link}\\n\\n👥 Convide um amigo para participar\\n${document.getElementById("groupLink")?.value||""}</div>`}
function addGroup(){let n=document.getElementById("groupName").value.trim();if(!n)return;groups.push(n);document.getElementById("groupName").value="";save();render()}
function render(){document.getElementById("countOffers").textContent=offers.length;document.getElementById("countQueue").textContent=queue.length;document.getElementById("countLinks").textContent=offers.filter(x=>x.link).length;document.getElementById("countPublished").textContent=history.length;
let list=document.getElementById("offersList");list.innerHTML=offers.length?offers.map(o=>`<div class="offer"><div class="offer-photo">🛍️</div><div class="offer-body"><span class="tag">${o.category}</span><h3>${esc(o.name)}</h3><div class="old">${esc(o.old||"")}</div><div class="price">${esc(o.price)}</div><p class="muted">🔗 Link cadastrado</p><button class="gold" onclick="makePreview(${JSON.stringify(o).replace(/"/g,'&quot;')})">Ver divulgação</button></div></div>`).join(""):`<div class="empty">Nenhuma oferta cadastrada.</div>`;
document.getElementById("recentOffers").innerHTML=offers.slice(0,5).map(o=>`<div class="queue-item"><b>${esc(o.name)}</b><br><span class="muted">${esc(o.price)} • ${esc(o.date)}</span></div>`).join("")||`<div class="empty">Nenhuma oferta cadastrada ainda.</div>`;
document.getElementById("queueList").innerHTML=queue.map((o,i)=>`<div class="queue-item"><b>${esc(o.name)}</b><br><span class="muted">${esc(o.price)} • aguardando publicação</span></div>`).join("")||`<div class="empty">Nenhuma oferta na fila.</div>`;
document.getElementById("historyList").innerHTML=history.map(o=>`<div class="history-item"><b>${esc(o.name)}</b><br><span class="muted">${esc(o.date)}</span></div>`).join("")||`<div class="empty">Nenhuma publicação registrada.</div>`;
document.getElementById("groupsList").innerHTML=groups.map(g=>`<div class="group"><span>👥 ${esc(g)}</span><span>✓</span></div>`).join("")}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
render();